# Generated by Django 5.0 on 2024-02-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='documents')),
                ('song', models.FileField(upload_to='documents')),
            ],
        ),
    ]
