# Generated by Django 5.0 on 2024-03-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_song_language_playhistory_delete_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English')], default='Hindi', max_length=20),
        ),
        migrations.DeleteModel(
            name='PlayHistory',
        ),
    ]
