# Generated by Django 5.0 on 2024-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_song_language_delete_playhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(default='Hindi', max_length=20),
        ),
    ]
